version: '3.8'

services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: bsdev
      POSTGRES_PASSWORD: bsdev
      POSTGRES_DB: bookingsystemDB
    ports:
      - "5432:5432"
    volumes:
      - dbdata:/var/lib/postgresql/data

  app:
    image: bookinsysteimage
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      DB_URL: jdbc:postgresql://localhost:5432/bookingsystemDB
      DB_USERNAME: postgres
      DB_PASSWORD: passw0rd

volumes:
  dbdata: